# Generated by Django 3.1.2 on 2020-10-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='evlluation',
            new_name='evaluation',
        ),
    ]
